# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: java ci with maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up jdk14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: test
        run: |
          cd spring-cloud-contract-server
          mvn clean spring-cloud-contract:generateTests
          mvn test
